<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<OutputType>Library</OutputType>
		<LangVersion>latest</LangVersion>
		
		<AssemblyName>DawnOfANewDay</AssemblyName>
		<RootNamespace>DawnNewDay</RootNamespace>
		<Authors>AlenDio</Authors>
		
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

		<Configurations>1.6;1.5</Configurations>
		
		<RWVersion Condition="'$(RWVersion)' == ''">1.6</RWVersion>
		<RWVersion Condition="'$(Configuration)' == '1.5'">1.5</RWVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RWVersion)' == '1.6'">
		<OutputPath>..\..\1.6\Assemblies\</OutputPath>
		<DefineConstants>RW_16</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(RWVersion)' == '1.5'">
		<OutputPath>..\..\1.5\Assemblies\</OutputPath>
		<DefineConstants>RW_15</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='1.6'">
		<DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='1.5'">
		<DebugType>none</DebugType>
	</PropertyGroup>
	
	<ItemGroup Condition="'$(RWVersion)' == '1.6'">
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" PrivateAssets="All" />
	</ItemGroup>
	<ItemGroup Condition="'$(RWVersion)' == '1.5'">
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.*" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Lib.Harmony" Version="2.4.2" ExcludeAssets="runtime" />
	</ItemGroup>
	
	<Target Name="PrintVersionMessage" BeforeTargets="Build">
		<Message Text="&gt; $(AssemblyName) for RimWorld $(RWVersion)" Importance="high" />
	</Target>

</Project>
