<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<OutputType>Library</OutputType>
		
		<AssemblyName>DawnOfANewDay</AssemblyName>
		<RootNamespace>DawnNewDay</RootNamespace>
		<Authors>AlenDio</Authors>
		
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		
		<RWVersion Condition="'$(RWVersion)' == ''">1.6</RWVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RWVersion)' == '1.6'">
		<OutputPath>..\..\1.6\Assemblies\</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(RWVersion)' == '1.5'">
		<OutputPath>..\..\1.5\Assemblies\</OutputPath>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup Condition="'$(RWVersion)' == '1.6'">
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" PrivateAssets="All" />
	</ItemGroup>
	<ItemGroup Condition="'$(RWVersion)' == '1.5'">
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.*" PrivateAssets="All" />
	</ItemGroup>
	
	<Target Name="PrintVersionMessage" BeforeTargets="Build">
		<Message Text="&gt; $(AssemblyName) for RimWorld $(RWVersion)" Importance="high" />
	</Target>
	
	<Target Name="BuilExtraVersions" AfterTargets="Build" Condition="'$(IsSecondaryBuild)' == ''">
		<MSBuild Projects="$(MSBuildProjectFullPath)" Targets="Build" Properties="Configuration=$(Configuration);RWVersion=1.5;IsSecondaryBuild=true" />
	</Target>

</Project>
